/// Data model representing a single chat message.
library;

/// The role of the message author.
enum MessageRole {
  /// A message sent by the user.
  user,

  /// A message generated by the AI assistant.
  assistant,
}

/// An immutable representation of one chat message.
class ChatMessage {
  /// Unique identifier for this message (used as a Flutter list key).
  final String id;

  /// Who sent this message.
  final MessageRole role;

  /// The text content of the message.
  final String content;

  /// When the message was created (local device time).
  final DateTime timestamp;

  const ChatMessage({
    required this.id,
    required this.role,
    required this.content,
    required this.timestamp,
  });

  /// Creates a user message with a generated ID and current timestamp.
  factory ChatMessage.user(String content) => ChatMessage(
        id: '${DateTime.now().microsecondsSinceEpoch}_u',
        role: MessageRole.user,
        content: content,
        timestamp: DateTime.now(),
      );

  /// Creates an assistant message with a generated ID and current timestamp.
  factory ChatMessage.assistant(String content) => ChatMessage(
        id: '${DateTime.now().microsecondsSinceEpoch}_a',
        role: MessageRole.assistant,
        content: content,
        timestamp: DateTime.now(),
      );

  /// Whether this message was sent by the user.
  bool get isUser => role == MessageRole.user;

  /// Whether this message was sent by the assistant.
  bool get isAssistant => role == MessageRole.assistant;

  @override
  String toString() =>
      'ChatMessage(role: $role, content: "${content.substring(0, content.length.clamp(0, 40))}...")';
}
